### PR TITLE
Added support of go 1.19 🚀

### PR DESCRIPTION
**Pull request by maZahaca**

### CODE REVIEW

**Comment by kuritka** [comment]
Hi @maZahaca 
It looks like this project froze more than two years ago (see the latest changes and closed PR's).

For building you can use `actions/setup-go@v2` see: [example](https://github.com/k8gb-io/k8gb/blob/master/.github/workflows/build.yml).


Good Luck

**Review by kuritka — APPROVED** [review]
Even though I'm not a maintainer, let's try to approve  😄

**Comment by maZahaca** [comment]
@kuritka Thanks for letting me know.
I specifically need a pipeline for building/publishing the golang project on the release stage. If you have an example for it, that would be great.
For this project, it seems the pipeline doesn't really work for older versions of go.

**Comment by kuritka** [comment]
@maZahaca , sure. 

For release , building container etc we use pipeline with go-releaser action,  see [this](https://github.com/k8gb-io/coredns-crd-plugin/blob/main/.github/workflows/release.yaml) which requires extra .yaml configuration within your project, see: [this](https://github.com/k8gb-io/coredns-crd-plugin/blob/main/.goreleaser.yml)

Here is one more (complex)example:  [pipeline](https://github.com/k8gb-io/k8gb/blob/master/.github/workflows/release.yaml), [ .goreleaser.yaml](https://github.com/k8gb-io/k8gb/blob/master/.goreleaser.yml)

If you just implement GO library module and you are ok with tags, [use these three pipelines](https://github.com/k8gb-io/go-weight-shuffling/tree/main/.github/workflows) within your project (test/build on multiple GO version, autotag, linting).

**Pull request merged**
